server:
  port: 34561
management:
  server:
    port: 12581
    address: 127.0.0.1
  endpoint:
    shutdown:
      enabled: true
  endpoints:
    web:
      base-path: /sd
      exposure:
        include: '*'
logging:
  config: classpath:logback-spring.xml
